services:
  frontend:
    container_name: frontend-ddne
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:4000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    networks:
      - network-ddne

  backend:
    container_name: backend-ddne
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - network-ddne
    
  mysql:
    container_name: database-ddne
    image: mysql:9.1.0
    environment:
      MYSQL_DATABASE: "database_ddne"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./services/mysql/data:/var/lib/mysql
      - ./services/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - network-ddne
    healthcheck:
      test: ["CMD", "sh", "-c", "mysql -uroot -e 'USE database_ddne; SHOW TABLES;'"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network-ddne:
    driver: bridge